//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCiHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISEASE_TYPE
    {
<<<<<<< HEAD
        public int DISEASE_ID { get; set; }
        public string DISEASE_NM { get; set; }
        public string DISEASE_DESCRIPTION { get; set; }
        public Nullable<int> SECTION_ID { get; set; }
=======
        public int Id { get; set; }
>>>>>>> 7fed91c79409195c8e0aa609f0f93479eb490f5c
    }
}
