//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCiHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPINFO
    {
        public int GROUP_ID { get; set; }
        public string GROUP_NM { get; set; }
        public int AUTHENTICATION { get; set; }
        public System.DateTime INSDATE { get; set; }
    }
}
