//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCiHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATIENT_HISTORY
    {
        public int HISTORY_ID { get; set; }
        public int PATIENT_ID { get; set; }
        public string HISTORY_URL { get; set; }
        public string PATIENT_IN { get; set; }
        public System.DateTime INSDATE { get; set; }
        public Nullable<System.DateTime> UPDATE { get; set; }
    }
}
