//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCiHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATIENT
    {
        public int PATIENT_ID { get; set; }
        public string PATIENT_NM { get; set; }
        public Nullable<System.DateTime> BIRTH { get; set; }
        public string GENDER { get; set; }
        public string TEL { get; set; }
        public string TEL2 { get; set; }
        public string EMAIL { get; set; }
        public string ADDRESS { get; set; }
        public string BLOOD_TYPE { get; set; }
        public string ALLERGIC_HISTORY { get; set; }
        public string GENETIC_HISTORY { get; set; }
        public string CAPITAL_OPERATION { get; set; }
        public string EMERGENCY_NAME { get; set; }
        public string EMERGENCY_TEL { get; set; }
        public string COMMENT { get; set; }
        public System.DateTime INSDATE { get; set; }
    }
}
