//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCiHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATION
    {
<<<<<<< HEAD
        public int RESERVATION_ID { get; set; }
        public Nullable<int> DOCTOR_ID { get; set; }
        public Nullable<int> PATIENT_ID { get; set; }
        public Nullable<System.DateTime> TIME_START { get; set; }
        public Nullable<System.DateTime> TIME_FINISH { get; set; }
        public string CONFIRMED { get; set; }
        public string VALID { get; set; }
        public string COMMENT { get; set; }
        public Nullable<System.DateTime> INSDATE { get; set; }
=======
        public int Id { get; set; }
>>>>>>> 7fed91c79409195c8e0aa609f0f93479eb490f5c
    }
}
