//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCiHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSLOG
    {
        public int LOG_ID { get; set; }
        public string SENDER { get; set; }
        public Nullable<int> TYPE { get; set; }
        public Nullable<int> LEVEL { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<int> AUTHORITY { get; set; }
        public Nullable<System.DateTime> INSDATE { get; set; }
        public Nullable<System.DateTime> OUTDATE { get; set; }
    }
}
