//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCiHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERINFO
    {
        public int USER_ID { get; set; }
        public string LOGIN_NM { get; set; }
        public string PASSWORD { get; set; }
        public int GROUP_ID { get; set; }
        public string EMAIL { get; set; }
        public string TEL { get; set; }
        public string COUNTORY { get; set; }
        public string PROVINCE { get; set; }
        public string CITY { get; set; }
        public string ADDRESS { get; set; }
        public string VALID { get; set; }
        public string DOC_URL { get; set; }
        public System.DateTime INSDATE { get; set; }
        public Nullable<System.DateTime> UPDATE { get; set; }
        public Nullable<System.DateTime> LASTLOGINTIME { get; set; }
    }
}
