/*以PATIENT表为例，根据姓名查询此人所属的用户组*/
SELECT
[P].[PATIENT_ID] AS [ID],
[P].PATIENT_NM AS [NAME],
[G].[GROUP_NM] AS [GROUP]
FROM
[PATIENT] AS [P]
LEFT JOIN [USERINFO] AS [U]/*左联接示例*/
ON [U].[USER_ID]=[P].PATIENT_ID
RIGHT JOIN [GROUPINFO] AS [G]/*右联接示例*/
ON [G].GROUP_ID=[U].GROUP_ID
WHERE
[P].PATIENT_NM='张三'
/*多查询联合*/
UNION
/*以DOCTOR表为例，根据姓名查询此人所属的用户组*/
SELECT
[D].[DOCTOR_ID] AS [ID],
[D].[DOCTOR_NM] AS [NAME],
[G].[GROUP_NM] AS [GROUP]
FROM
[DOCTOR] AS [D]
INNER JOIN [USERINFO] AS [U]/*内联接示例*/
ON [U].[USER_ID]=[D].DOCTOR_ID
FULL JOIN [GROUPINFO] AS [G]/*全联接示例*/
ON [G].GROUP_ID=[U].GROUP_ID
WHERE
[D].DOCTOR_NM='李四'